pattern_cols: 11
pattern_rows: 8
center_distance_mm: 15

# R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, -1]
# R_gimbal2imubody: [1, 0, 0, 0, -1, 0, 0, 0, 1]
# R_gimbal2imubody: [1, 0, 0, 0, -1, 0, 0, 0, -1]
# R_gimbal2imubody: [-1, 0, 0, 0, 1, 0, 0, 0, 1]
# R_gimbal2imubody: [-1, 0, 0, 0, 1, 0, 0, 0, -1]
# R_gimbal2imubody: [-1, 0, 0, 0, -1, 0, 0, 0, 1]
# R_gimbal2imubody: [-1, 0, 0, 0, -1, 0, 0, 0, -1]

# IMU数据源选择: "gimbal" "can" 或 "dm_imu"
# can: 通过CAN总线(CBoard)读取IMU数据
# dm_imu: 通过串口(DM_IMU)读取IMU数据
imu_source: "gimbal"
com_port: "/dev/ttyACM0"

camera_name: "hikrobot"
exposure_ms: 15
gain: 10.0
vid_pid: "2bdf:0001"
image_rotate_180: false

#####-----cboard参数（仅在使用can时需要）-----#####
# 当imu_source为"can"时，需要取消注释以下参数
# quaternion_canid: 0x01
# bullet_speed_canid: 0x110
# send_canid: 0xff
# can_interface: "can0"

# 重投影误差: 0.1911px
camera_matrix: [2402.224336112246, 0, 706.01196211204569, 0, 2400.2518274119602, 550.68934831776346, 0, 0, 1]
distort_coeffs: [-0.028615064812785442, 0.12071167341048554, -0.0011606232796259556, 0.00032278455334136601, 0]