enemy_color: "red"
# enemy_color: "blue"

#####-----神经网络参数-----#####
backend: openvino
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo26n_model_path: assets/best_fp32.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: GPU
min_confidence: 0.8
use_traditional: false

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----工业相机参数-----#####
camera_name: "hikrobot"
exposure_ms: 8
gain: 5.0
vid_pid: "2bdf:0001"
image_rotate_180: true

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 0 # degree
pitch_offset: 0 # degree
comming_angle: 55 # degree
leaving_angle: 20 # degree
decision_speed: 7 # rad/s
high_speed_delay_time: 0.0 # s
low_speed_delay_time: 0.0 # s planner use this value

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----工业相机标定参数-----#####
# 重投影误差: 0.1840px
camera_matrix: [1802.1719526069726, 0, 721.92876481566952, 0, 1803.3806313111968, 569.56345908002345, 0, 0, 1]
distort_coeffs: [-0.09261507425518023, 0.22187246728557139, 0.00075669972573856408, 0.0014021340601661364, 0]

R_gimbal2imubody: [-1, 0, 0, 0, 1, 0, 0, 0, 1]

# 相机同理想情况的偏角: yaw0.93 pitch2.19 roll-3.49 degree
# 标定板到世界坐标系原点的水平距离: 0.69 m
# 标定板同竖直摆放时的偏角: yaw69.76 pitch-3.90 roll177.47 degree
R_camera2gimbal: [-0.018555013094418499, 0.037192843841034169, 0.99913582853187821, -0.99797811811486425, -0.061447038094837481, -0.016246146413406468, 0.060789696931142854, -0.99741714135881387, 0.038257794900278239]
t_camera2gimbal: [0.10683127808138922, -0.0012247206563364269, -0.038899075919945895]

#####-----gimbal参数-----#####
com_port: "/dev/ttyACM0"
yaw_kp: 0
yaw_kd: 0
pitch_kp: 0
pitch_kd: 0

#####-----planner-----#####
fire_thresh: 0.0035

# 求解器类型选择: "mpc" 或 "quintic_poly"
# solver_type: "quintic_poly"
solver_type: "mpc"

# MPC求解器参数（仅在solver_type="mpc"时使用）
max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

# 五次多项式求解器参数（仅在solver_type="quintic_poly"时使用）
max_yaw_vel: 5.0      # yaw轴最大角速度（rad/s）
max_yaw_acc: 5.0      # yaw轴最大角加速度（rad/s²）
max_pitch_vel: 5.0    # pitch轴最大角速度（rad/s）
max_pitch_acc: 5.0   # pitch轴最大角加速度（rad/s²）
jump_threshold: 0.05     # 突变检测阈值（rad/s），相邻时间步角速度（斜率）变化超过此值则认为是突变
